[
  'Karnataka',
  'Andhra Pradesh',
  'Tamil Nadu',
  'Telangana',
  'Uttar Pradesh',
  'Maharashtra',
  'Madhya Pradesh',
  'Kerala',
  'Gujarat',
  'West Bengal',
  'Punjab',
  'Rajasthan',
  'Uttarakhand',
  'Chhattisgarh',
  'Haryana',
  'Jharkhand',
  'Odisha',
  'Bihar',
  'Delhi',
  'Chandigarh',
  'Himachal Pradesh',
  'Tripura',
  'Assam',
  'Goa',
  'Dadra and Nagar Haveli',
  'Andaman and Nicobar Islands',
  'Puducherry',
  'Sikkim',
  'Jammu and Kashmir',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Arunachal Pradesh'
].each do |name_of_state|
  State.where(name: name_of_state).first_or_create!
end
