amazon: &amazon
  service: S3
  access_key_id: <%= Rails.application.secrets.aws[:access_key_id] %>
  secret_access_key: <%= Rails.application.secrets.aws[:secret_access_key] %>
  bucket: <%= Rails.application.secrets.aws[:bucket_public] %>
  region: <%= Rails.application.secrets.aws[:region] %>
  public: true

amazon_private:
  <<: *amazon
  bucket: <%= Rails.application.secrets.aws[:bucket_private] %>
