Rails.application.config.assets.precompile += %w(
  easyrtc_video.js
  active_admin_custom.js
  active_admin_custom.css
  select2.png
  mails.css
  pnotify.css
  timeline.css
  owl-carousel/owl.carousel.css
  general_style.css
  icon/component.css
  icon/modernizr.custom.js
  homepage.js
  timeline.js
  owl-carousel/owl.carousel.js
  ct-carousel/masonry.pkgd.min.js
  flexslider/jquery.flexslider-min.js
  flexslider/flexslider.css
)
