require_relative 'oembed/base_provider'
require_relative 'oembed/slideshare_provider'
require_relative 'oembed/youtube_provider'
require_relative 'oembed/vimeo_provider'
require_relative 'oembed/resolver'
require_relative 'oembed/generic_provider'
require_relative 'oembed/g_slide_fallback_provider'
