// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var DateFns = require("date-fns");

function parse(s) {
  return DateFns.parse(s);
}

function format(f, t) {
  var formatString = f ? "MMM D HH:mm" : "Do MMM YYYY";
  return DateFns.format(t, formatString);
}

exports.parse = parse;
exports.format = format;
/* date-fns Not a pure module */
