// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");

function decode(json) {
  return /* record */[
          /* title */Json_decode.field("title", Json_decode.string, json),
          /* id */Json_decode.field("id", Json_decode.$$int, json)
        ];
}

function title(t) {
  return t[/* title */0];
}

function id(t) {
  return t[/* id */1];
}

exports.decode = decode;
exports.title = title;
exports.id = id;
/* No side effect */
