// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Json_encode = require("@glennsl/bs-json/src/Json_encode.bs.js");
var PNotify = require("pnotify/dist/es/PNotify");

function success(title, text) {
  PNotify.default.success(Json_encode.object_(/* :: */[
            /* tuple */[
              "title",
              title
            ],
            /* :: */[
              /* tuple */[
                "text",
                text
              ],
              /* :: */[
                /* tuple */[
                  "styling",
                  "bootstrap4"
                ],
                /* :: */[
                  /* tuple */[
                    "delay",
                    4000
                  ],
                  /* [] */0
                ]
              ]
            ]
          ]));
  return /* () */0;
}

function error(title, text) {
  PNotify.default.error(Json_encode.object_(/* :: */[
            /* tuple */[
              "title",
              title
            ],
            /* :: */[
              /* tuple */[
                "text",
                text
              ],
              /* :: */[
                /* tuple */[
                  "styling",
                  "bootstrap4"
                ],
                /* :: */[
                  /* tuple */[
                    "delay",
                    4000
                  ],
                  /* [] */0
                ]
              ]
            ]
          ]));
  return /* () */0;
}

exports.success = success;
exports.error = error;
/* Json_encode Not a pure module */
