// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");
var Link$ReactTemplate = require("./Link.bs.js");
var DateTime$ReactTemplate = require("./DateTime.bs.js");

function parseStatus(status) {
  switch (status) {
    case "Needs Improvement" : 
        return /* NeedsImprovement */3;
    case "Not Accepted" : 
        return /* NotAccepted */1;
    case "Pending" : 
        return /* Pending */2;
    case "Verified" : 
        return /* Verified */0;
    default:
      return Pervasives.failwith("Invalid Status");
  }
}

function decode(json) {
  return /* record */[
          /* id */Json_decode.field("id", Json_decode.$$int, json),
          /* title */Json_decode.field("title", Json_decode.string, json),
          /* description */Json_decode.field("description", Json_decode.string, json),
          /* status */parseStatus(Json_decode.field("status", Json_decode.string, json)),
          /* eventOn */DateTime$ReactTemplate.parse(Json_decode.field("eventOn", Json_decode.string, json)),
          /* startupId */Json_decode.field("startupId", Json_decode.$$int, json),
          /* startupName */Json_decode.field("startupName", Json_decode.string, json),
          /* founderId */Json_decode.field("founderId", Json_decode.$$int, json),
          /* founderName */Json_decode.field("founderName", Json_decode.string, json),
          /* submittedAt */DateTime$ReactTemplate.parse(Json_decode.field("submittedAt", Json_decode.string, json)),
          /* links */Json_decode.field("links", (function (param) {
                  return Json_decode.list(Link$ReactTemplate.decode, param);
                }), json)
        ];
}

function forStartupId(startupId, tes) {
  return List.filter((function (te) {
                  return te[/* startupId */5] === startupId;
                }))(tes);
}

function verificationPending(tes) {
  return List.filter((function (te) {
                  return te[/* status */3] === /* Pending */2;
                }))(tes);
}

function verificationComplete(tes) {
  return List.filter((function (te) {
                  return te[/* status */3] !== /* Pending */2;
                }))(tes);
}

function id(t) {
  return t[/* id */0];
}

function title(t) {
  return t[/* title */1];
}

function description(t) {
  return t[/* description */2];
}

function founderName(t) {
  return t[/* founderName */8];
}

function startupName(t) {
  return t[/* startupName */6];
}

function submittedAt(t) {
  return t[/* submittedAt */9];
}

exports.title = title;
exports.submittedAt = submittedAt;
exports.description = description;
exports.founderName = founderName;
exports.startupName = startupName;
exports.id = id;
exports.forStartupId = forStartupId;
exports.verificationPending = verificationPending;
exports.verificationComplete = verificationComplete;
exports.decode = decode;
/* DateTime-ReactTemplate Not a pure module */
