// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var DateTime$ReactTemplate = require("./DateTime.bs.js");

function parseStatus(status) {
  switch (status) {
    case "Needs Improvement" : 
        return /* NeedsImprovement */3;
    case "Not Accepted" : 
        return /* NotAccepted */1;
    case "Pending" : 
        return /* Pending */2;
    case "Verified" : 
        return /* Verified */0;
    default:
      return Pervasives.failwith("Invalid Status");
  }
}

var JsDecode = /* module */[/* parseStatus */parseStatus];

function create(js_t) {
  return /* record */[
          /* id */js_t.id,
          /* title */js_t.title,
          /* description */js_t.description,
          /* status */parseStatus(js_t.status),
          /* eventOn */DateTime$ReactTemplate.parse(js_t.eventOn),
          /* startupId */js_t.startupId,
          /* startupName */js_t.startupName,
          /* founderId */js_t.founderId,
          /* founderName */js_t.founderName,
          /* submittedAt */DateTime$ReactTemplate.parse(js_t.submittedAt)
        ];
}

function forStartupId(startupId, tes) {
  return List.filter((function (te) {
                  return te[/* startupId */5] === startupId;
                }))(tes);
}

function verificationPending(tes) {
  return List.filter((function (te) {
                  return te[/* status */3] === /* Pending */2;
                }))(tes);
}

function verificationComplete(tes) {
  return List.filter((function (te) {
                  return te[/* status */3] !== /* Pending */2;
                }))(tes);
}

function title(t) {
  return t[/* title */1];
}

function description(t) {
  return t[/* description */2];
}

function eventOn(t) {
  return t[/* eventOn */4];
}

function founderId(t) {
  return t[/* founderId */7];
}

function founderName(t) {
  return t[/* founderName */8];
}

function startupId(t) {
  return t[/* startupId */5];
}

function startupName(t) {
  return t[/* startupName */6];
}

function submittedAt(t) {
  return t[/* submittedAt */9];
}

exports.JsDecode = JsDecode;
exports.create = create;
exports.forStartupId = forStartupId;
exports.verificationPending = verificationPending;
exports.verificationComplete = verificationComplete;
exports.title = title;
exports.description = description;
exports.eventOn = eventOn;
exports.founderId = founderId;
exports.founderName = founderName;
exports.startupId = startupId;
exports.startupName = startupName;
exports.submittedAt = submittedAt;
/* DateTime-ReactTemplate Not a pure module */
