# Do not keep production secrets in the repository,
# instead read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.
secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
