require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe StartupsController do
  login_user
  # This should return the minimal set of attributes required to create a valid
  # Startup. As you add validations to Startup, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    attributes_for(:startup)
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # StartupsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all startups as @startups" do
      startup = Startup.create! valid_attributes
      @current_user.update_attributes(startup: startup)
      get :index, {}, valid_session
      expect(assigns(:startups)).to eq([startup])
    end

    it "assigns empty array to @startups if user dosent' have a startup linked" do
      get :index, {}, valid_session
      expect(assigns(:startups)).to eq([])
    end
  end

  describe "GET show" do
    it "assigns the requested startup as @startup" do
      startup = Startup.create! valid_attributes
      @current_user.update_attributes(startup: startup)
      get :show, {:id => startup.to_param}, valid_session
      expect(assigns(:startup)).to eq(startup)
    end
  end

  describe "GET new" do
    it "assigns a new startup as @startup" do
      get :new, {}, valid_session
      expect(assigns(:startup)).to be_a_new(Startup)
    end
  end

  describe "GET edit" do
    it "assigns the requested startup as @startup" do
      startup = Startup.create! valid_attributes
      @current_user.update_attributes(startup: startup)
      get :edit, {:id => startup.to_param}, valid_session
      expect(assigns(:startup)).to eq(startup)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Startup" do
        expect {
          post :create, {:startup => valid_attributes}, valid_session
        }.to change(Startup, :count).by(1)
      end

      it "assigns a newly created startup as @startup" do
        post :create, {:startup => valid_attributes}, valid_session
        expect(assigns(:startup)).to be_a(Startup)
        expect(assigns(:startup)).to be_persisted
      end

      it "redirects to the created startup" do
        post :create, {:startup => valid_attributes}, valid_session
        expect(response).to redirect_to(Startup.last)
      end
    end

  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested startup" do
        startup = Startup.create! valid_attributes
        # Assuming there are no other startups in the database, this
        # specifies that the Startup created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        expect_any_instance_of(Startup).to receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => startup.to_param, :startup => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested startup as @startup" do
        startup = Startup.create! valid_attributes
        put :update, {:id => startup.to_param, :startup => valid_attributes}, valid_session
        expect(assigns(:startup)).to eq(startup)
      end

      it "redirects to the startup" do
        startup = Startup.create! valid_attributes
        put :update, {:id => startup.to_param, :startup => valid_attributes}, valid_session
        expect(response).to redirect_to(startup)
      end
    end

    describe "with invalid params" do
      it "assigns the startup as @startup" do
        startup = Startup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Startup.any_instance.stub(:save).and_return(false)
        put :update, {:id => startup.to_param, :startup => { "name" => nil }}, valid_session
        expect(assigns(:startup)).to eq(startup)
      end

    end
  end

  describe "DELETE destroy" do
    it "destroys the requested startup" do
      startup = Startup.create! valid_attributes
      expect {
        delete :destroy, {:id => startup.to_param}, valid_session
      }.to change(Startup, :count).by(-1)
    end

    it "redirects to the startups list" do
      startup = Startup.create! valid_attributes
      delete :destroy, {:id => startup.to_param}, valid_session
      expect(response).to redirect_to(startups_url)
    end
  end

end
