// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var TimelineEvent$ReactTemplate = require("../types/TimelineEvent.bs.js");

((require("./ReviewStatusBadge.scss")));

function str(prim) {
  return prim;
}

var component = ReasonReact.statelessComponent("ReviewStatusBadge");

function containerClass(reviewedStatus) {
  return (
          typeof reviewedStatus === "number" ? (
              reviewedStatus !== 0 ? "review-status-badge__container--needs-improvement" : "review-status-badge__container--not-accepted"
            ) : "review-status-badge__container--verified"
        ) + " review-status-badge__container";
}

function faIcon(reviewedStatus) {
  return (
          typeof reviewedStatus === "number" ? (
              reviewedStatus !== 0 ? "fa-hourglass-half" : "fa-times"
            ) : "fa-check"
        ) + " fa mr-1";
}

function make(reviewedStatus, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("div", {
                          className: containerClass(reviewedStatus)
                        }, React.createElement("i", {
                              className: faIcon(reviewedStatus)
                            }), TimelineEvent$ReactTemplate.statusString(/* Reviewed */[reviewedStatus]));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.str = str;
exports.component = component;
exports.containerClass = containerClass;
exports.faIcon = faIcon;
exports.make = make;
/*  Not a pure module */
