// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var $$String = require("bs-platform/lib/js/string.js");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var TimelineEvent$ReactTemplate = require("../types/TimelineEvent.bs.js");

function str(prim) {
  return prim;
}

var component = ReasonReact.reducerComponent("ReviewForm");

function saveStatus(status, send, _) {
  return Curry._1(send, /* ChangeStatus */[status]);
}

function idPostfix(status) {
  if (typeof status === "number") {
    switch (status) {
      case 0 : 
          return "not-accepted";
      case 1 : 
          return "pending";
      case 2 : 
          return "needs-improvement";
      
    }
  } else {
    return "verified";
  }
}

function statusRadioInput(status, timelineEventId, send) {
  var inputId = "review-form__status-input-" + (idPostfix(status) + ("-" + timelineEventId));
  return React.createElement("div", {
              className: "form-check form-check-inline"
            }, React.createElement("input", {
                  className: "form-check-input",
                  id: inputId,
                  name: "review-form__status-radio-" + timelineEventId,
                  type: "radio",
                  onClick: (function () {
                      return Curry._1(send, /* ChangeStatus */[status]);
                    })
                }), React.createElement("label", {
                  className: "form-check-label",
                  htmlFor: inputId
                }, TimelineEvent$ReactTemplate.statusString(status)));
}

function gradeRadioInput(grade, timelineEventId, send, state) {
  var inputId = "review-form__grade-input-" + (TimelineEvent$ReactTemplate.gradeString(grade) + ("-" + timelineEventId));
  var partial_arg = /* Verified */[grade];
  return React.createElement("div", {
              className: "form-check form-check-inline"
            }, React.createElement("input", {
                  className: "form-check-input",
                  id: inputId,
                  checked: Caml_obj.caml_equal(TimelineEvent$ReactTemplate.status(state[/* te */0]), /* Verified */[grade]),
                  name: "review-form__grade-radio-" + timelineEventId,
                  type: "radio",
                  onChange: (function () {
                      return Curry._1(send, /* ChangeStatus */[partial_arg]);
                    })
                }), React.createElement("label", {
                  className: "form-check-label",
                  htmlFor: inputId
                }, $$String.capitalize(TimelineEvent$ReactTemplate.gradeString(grade))));
}

function make(timelineEvent, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */(function (param) {
              console.log("status: " + TimelineEvent$ReactTemplate.statusString(TimelineEvent$ReactTemplate.status(param[/* newSelf */1][/* state */1][/* te */0])));
              return /* () */0;
            }),
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (param) {
              var send = param[/* send */3];
              var state = param[/* state */1];
              var timelineEventId = String(TimelineEvent$ReactTemplate.id(state[/* te */0]));
              return React.createElement("div", undefined, React.createElement("h5", {
                              className: "timeline-event-card__field-header mt-0"
                            }, "Update Status:"), React.createElement("div", undefined, statusRadioInput(/* Verified */[/* Good */0], timelineEventId, send), statusRadioInput(/* NeedsImprovement */2, timelineEventId, send), statusRadioInput(/* NotAccepted */0, timelineEventId, send)), TimelineEvent$ReactTemplate.isVerified(state[/* te */0]) ? React.createElement("div", undefined, React.createElement("h5", {
                                    className: "timeline-event-card__field-header"
                                  }, "Grade:"), React.createElement("div", undefined, gradeRadioInput(/* Good */0, timelineEventId, send, state), gradeRadioInput(/* Great */1, timelineEventId, send, state), gradeRadioInput(/* Wow */2, timelineEventId, send, state))) : null, TimelineEvent$ReactTemplate.status(state[/* te */0]) !== /* Pending */1 ? React.createElement("button", {
                                className: "btn btn-primary mt-1"
                              }, "Save Review") : null);
            }),
          /* initialState */(function () {
              return /* record */[/* te */timelineEvent];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, _) {
              return /* Update */Block.__(0, [/* record */[/* te */TimelineEvent$ReactTemplate.updateStatus(action[0], timelineEvent)]]);
            }),
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.str = str;
exports.component = component;
exports.saveStatus = saveStatus;
exports.idPostfix = idPostfix;
exports.statusRadioInput = statusRadioInput;
exports.gradeRadioInput = gradeRadioInput;
exports.make = make;
/* component Not a pure module */
