// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

function str(prim) {
  return prim;
}

var component = ReasonReact.statelessComponent("StartupsList");

function make(startups, selectedStartupId, selectStartupCB, clearStartupCB, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("div", undefined, React.createElement("div", undefined, "Your startups:"), $$Array.of_list(List.map((function (startup) {
                                    var buttonClasses;
                                    if (selectedStartupId) {
                                      var match = selectedStartupId[0] === startup.id;
                                      buttonClasses = match ? "btn btn-primary" : "btn btn-secondary";
                                    } else {
                                      buttonClasses = "btn btn-secondary";
                                    }
                                    return React.createElement("button", {
                                                key: startup.name,
                                                className: buttonClasses,
                                                onClick: (function () {
                                                    return Curry._1(selectStartupCB, startup.id);
                                                  })
                                              }, "Startup Name: " + startup.name);
                                  }), startups)), selectedStartupId ? React.createElement("button", {
                                onClick: (function () {
                                    return Curry._1(clearStartupCB, /* () */0);
                                  })
                              }, "Clear Filter") : null);
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.str = str;
exports.component = component;
exports.make = make;
/* component Not a pure module */
