// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Startup$ReactTemplate = require("../types/Startup.bs.js");

((require("./StartupsList.scss")));

function str(prim) {
  return prim;
}

var component = ReasonReact.statelessComponent("StartupsList");

function make(startups, selectedStartupId, selectStartupCB, clearStartupCB, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("div", {
                          className: "startups-list__container"
                        }, $$Array.of_list(List.map((function (startup) {
                                    var buttonClasses;
                                    if (selectedStartupId) {
                                      var match = selectedStartupId[0] === Startup$ReactTemplate.id(startup);
                                      buttonClasses = match ? "startups-list__item startups-list__item--selected" : "startups-list__item";
                                    } else {
                                      buttonClasses = "startups-list__item";
                                    }
                                    return React.createElement("button", {
                                                key: Startup$ReactTemplate.name(startup),
                                                className: buttonClasses,
                                                onClick: (function () {
                                                    return Curry._1(selectStartupCB, Startup$ReactTemplate.id(startup));
                                                  })
                                              }, Startup$ReactTemplate.name(startup));
                                  }), startups)), selectedStartupId ? React.createElement("button", {
                                className: "startups-list__clear-filter-btn",
                                onClick: (function () {
                                    return Curry._1(clearStartupCB, /* () */0);
                                  })
                              }, "Show All") : null);
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.str = str;
exports.component = component;
exports.make = make;
/*  Not a pure module */
