// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var TimelineEvent$ReactTemplate = require("../types/TimelineEvent.bs.js");
var TimelineEventsList$ReactTemplate = require("./TimelineEventsList.bs.js");

((require("./TimelineEventsPanel.scss")));

function str(prim) {
  return prim;
}

var component = ReasonReact.statelessComponent("TimelineEventsPanel");

function startupFilter(startupId, tes) {
  if (startupId) {
    return TimelineEvent$ReactTemplate.forStartupId(startupId[0], tes);
  } else {
    return tes;
  }
}

function make(timelineEvents, selectedStartupId, authenticityToken, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("div", {
                          className: "timeline-events-panel__container"
                        }, React.createElement("h3", undefined, "Pending"), React.createElement("hr", undefined), ReasonReact.element(/* None */0, /* None */0, TimelineEventsList$ReactTemplate.make(TimelineEvent$ReactTemplate.verificationPending(startupFilter(selectedStartupId, timelineEvents)), authenticityToken, /* array */[])), React.createElement("h3", undefined, "Complete"), React.createElement("hr", undefined), ReasonReact.element(/* None */0, /* None */0, TimelineEventsList$ReactTemplate.make(TimelineEvent$ReactTemplate.verificationComplete(startupFilter(selectedStartupId, timelineEvents)), authenticityToken, /* array */[])));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.str = str;
exports.component = component;
exports.startupFilter = startupFilter;
exports.make = make;
/*  Not a pure module */
