// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Fetch = require("bs-fetch/src/Fetch.js");
var React = require("react");
var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");
var Notification$ReactTemplate = require("../types/Notification.bs.js");
var TimelineEvent$ReactTemplate = require("../types/TimelineEvent.bs.js");

((require("./UndoReviewButton.scss")));

var UnexpectedResponse = Caml_exceptions.create("UndoReviewButton-ReactTemplate.UnexpectedResponse");

function handleApiError(match) {
  if (Caml_exceptions.isCamlExceptionOrOpenVariant(match) && match[0] === UnexpectedResponse) {
    return /* Some */[match[1]];
  } else {
    return /* None */0;
  }
}

function str(prim) {
  return prim;
}

var component = ReasonReact.statelessComponent("UndoReviewButton");

function handleResponseJSON(te, replaceTE_CB, json) {
  var match = Json_decode.field("error", (function (param) {
          return Json_decode.nullable(Json_decode.string, param);
        }), json);
  if (match !== null) {
    console.log(match);
    return /* () */0;
  } else {
    Notification$ReactTemplate.success("Review Reverted", "Review cleared and moved to pending");
    return Curry._1(replaceTE_CB, TimelineEvent$ReactTemplate.updateStatus(/* NotReviewed */0, te));
  }
}

function undoReview(te, replaceTE_CB, _) {
  var id = String(TimelineEvent$ReactTemplate.id(te));
  fetch("/timeline_events/" + (id + "/undo_review"), Fetch.RequestInit[/* make */0](/* Some */[/* Post */2], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[/* SameOrigin */1], /* None */0, /* None */0, /* None */0, /* None */0)(/* () */0)).then((function (response) {
              if (response.ok || response.status === 422) {
                return response.json();
              } else {
                return Promise.reject([
                            UnexpectedResponse,
                            response.status
                          ]);
              }
            })).then((function (json) {
            return Promise.resolve(handleResponseJSON(te, replaceTE_CB, json));
          })).catch((function (error) {
          var match = handleApiError(error);
          return Promise.resolve(match ? Notification$ReactTemplate.error(String(match[0]), "Please try again") : Notification$ReactTemplate.error("Something went wrong!", "Please try again"));
        }));
  return /* () */0;
}

function make(timelineEvent, replaceTE_CB, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("button", {
                          className: "btn btn-primary undo-review-btn mt-1",
                          onClick: (function (param) {
                              return undoReview(timelineEvent, replaceTE_CB, param);
                            })
                        }, React.createElement("i", {
                              className: "fa fa-undo mr-1"
                            }), "Undo Review");
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.UnexpectedResponse = UnexpectedResponse;
exports.handleApiError = handleApiError;
exports.str = str;
exports.component = component;
exports.handleResponseJSON = handleResponseJSON;
exports.undoReview = undoReview;
exports.make = make;
/*  Not a pure module */
