name: Combine Dependencies

on: workflow_dispatch

# The minimum permissions required to run this Action
permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  combine-prs:
    runs-on: ubuntu-latest

    steps:
      - name: Combine dependencies
        id: combine-dependencies
        uses: github/combine-prs@v5.0.0
        with:
          pr_title: Combined dependencies # The title of the pull request to create
          select_label: dependencies # The label which marks PRs that should be combined.
          labels: combined-dependencies # Add a label to the combined PR
          ci_required: "false" # Whether or not CI should be passing to combine the PR
